# Generated by Django 4.0.2 on 2022-03-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installmentS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Account', models.IntegerField()),
                ('Phone_no', models.IntegerField()),
                ('Idcardno', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Debt', models.IntegerField()),
            ],
        ),
    ]
