# Generated by Django 4.0.2 on 2022-03-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installmentS', '0002_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='poinofsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Accountnumber', models.IntegerField()),
                ('Customername', models.CharField(max_length=100)),
                ('Productname', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Downpayment', models.IntegerField()),
                ('Totalinstallment', models.IntegerField()),
                ('Perinstallment', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Paid', models.IntegerField()),
                ('Remaininginstallment', models.IntegerField()),
            ],
        ),
    ]
